[config]

[templates.quickshell-colors]
input_path  = "~/.config/matugen/templates/quickshell-colors.json"
output_path = "~/.config/quickshell/theme/colors.json"

[templates.tmux-colors]
input_path  = "~/.config/matugen/templates/tmux-colors.conf"
output_path = "~/.config/tmux/colors.conf"

[templates.kitty]
input_path  = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/theme.conf"

[templates.yazi-theme]
input_path  = "~/.config/matugen/templates/yazi-theme.toml"
output_path = "~/.config/yazi/theme.toml"

[templates.hyprlock]
input_path  = "~/.config/matugen/templates/hyprlock.conf"
output_path = "~/.config/hypr/hyprlock.conf"

[templates.gtk3]
input_path  = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/gtk.css"

[templates.gtk4]
input_path  = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/gtk.css"
