device {
    name = asup1205:00-093a:2008-touchpad

    enabled = true

    # Recommended touchpad options
    natural_scroll = true
    clickfinger_behavior = true
    scroll_factor = 0.8
    sensitivity = 0.6
    middle_button_emulation = true
}

