#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = fcitx5 &
exec-once = swww-daemon
exec-once = sleep 2 && ~/.config/hypr/scripts/wallpaper-cycle.sh &
exec-once = sleep 2 && matugen -c ~/.config/matugen/config-lock.toml image /home/jp/dotfiles/wallpapers/lock.jpeg
exec-once = sleep 4 && quickshell &
exec-once = cursor-clip --daemon
