#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = fcitx5 &
exec-once = awww-daemon
exec = pkill quickshell; quickshell &
exec-once = cursor-clip --daemon
