general {
    hide_cursor = true
    grace = 5
}

background {
    monitor =
    path = /home/jp/dotfiles/wallpapers/lock.jpeg
    blur_passes = 1
    blur_size = 4
    noise = 0.01
    contrast = 0.9
    brightness = 0.5
    vibrancy = 0.17
    vibrancy_darkness = 0.0
}

# Date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(ffffffee)
    font_size = 20
    font_family = SF Pro Display Bold
    position = 0, 405
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 5
    shadow_color = rgba(000000aa)
    shadow_boost = 2.0
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%k:%M")"
    color = rgba(ffffffee)
    font_size = 93
    font_family = SF Pro Display Bold
    position = 0, 310
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 5
    shadow_color = rgba(000000aa)
    shadow_boost = 2.0
}

input-field {
    monitor =
    size = 300, 30
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.55
    dots_center = true
    dots_rounding = -1
    outer_color = rgba({{colors.primary.dark.hex_stripped}}aa)
    inner_color = rgba(1a1a1aee)
    font_color = rgba(ffffffee)
    fade_on_empty = false
    placeholder_text =
    hide_input = false
    check_color = rgba({{colors.primary.light.hex_stripped}}00)
    fail_color = rgba({{colors.error.light.hex_stripped}}00)
    fail_text = $FAIL <b>($ATTEMPTS)</b>
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -468
    halign = center
    valign = center
}
